AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: AWS Lambda sample by Rust
Resources:
  RustRuntimeSampleTest:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rust-lambda-sample
      CodeUri: target/x86_64-unknown-linux-musl/release
      Handler: bootstrap.is.real.handler
      Runtime: provided
      Tracing: Active
